### ISSUE TITLE
What do value1 and value2 represent respectively?

### ISSUE THREAD

**Issue by Peipeilvcm** [partofthestars/LGI-PPGI-DB#3]
```
<value612>
	<value0>612</value0>
	<value1>96</value1>
	<value2>66</value2>
</value612>
```

I guess that value1-value2 means the gound truth of Heart Rate. Am I right?

**Comment by partofthestars** [comment]
in the cms50 xml file value0 is the frame counter, value1 is the average heart rate computed on the device and value2 is the ppg time signal measured with the device.
